[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nusaturn", email = "skaturanus@proton.me" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]>=0.141.1",
    "uvicorn>=0.53.0",
    "pulumi>=3",
    "pulumi-aws>=6",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "httpx",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.coverage.run]
source = ["src"]
